// Demo data — replace with real API data later

export const DEMO_PROFILE = {
  name: "Linus Torvalds",
  username: "torvalds",
  bio: "Nothing to see here. Linux kernel developer and open source advocate.",
  location: "Portland, OR",
  blog: "linuxfoundation.org",
  avatarUrl: "https://avatars.githubusercontent.com/u/1024025?v=4",
  followers: 241000,
  following: 0,
  publicRepos: 8,
};

export const DEMO_STATS = {
  publicRepos: 8,
  totalStars: 198400,
  totalForks: 56200,
  followers: 241000,
};

export const DEMO_LANGUAGES = [
  { name: "JavaScript", percent: 42, color: "#F7DF1E" },
  { name: "TypeScript", percent: 28, color: "#3178C6" },
  { name: "Python", percent: 14, color: "#3572A5" },
  { name: "CSS", percent: 10, color: "#563D7C" },
  { name: "Shell", percent: 6, color: "#89E051" },
];

export const DEMO_REPOS = [
  {
    id: 1,
    name: "linux",
    description: "Linux kernel source tree — the foundation of modern operating systems.",
    language: "C++",
    stars: 198000,
    forks: 56100,
    visibility: "public",
    updatedAt: "Jun 18, 2026",
    url: "https://github.com/torvalds/linux",
  },
  {
    id: 2,
    name: "subsurface-for-dirk",
    description: "A sample project for testing and demonstration purposes.",
    language: "C++",
    stars: 1200,
    forks: 340,
    visibility: "public",
    updatedAt: "May 30, 2026",
    url: "#",
  },
  {
    id: 3,
    name: "devlens-core",
    description: "Core analytics engine powering the DevLens productivity dashboard.",
    language: "TypeScript",
    stars: 3400,
    forks: 420,
    visibility: "public",
    updatedAt: "Jun 15, 2026",
    url: "#",
  },
  {
    id: 4,
    name: "react-query-toolkit",
    description: "Utilities and hooks built on top of TanStack Query for enterprise apps.",
    language: "TypeScript",
    stars: 870,
    forks: 92,
    visibility: "public",
    updatedAt: "Jun 10, 2026",
    url: "#",
  },
  {
    id: 5,
    name: "open-source-guide",
    description: "A comprehensive guide to maintaining open source projects at scale.",
    language: "Markdown",
    stars: 2200,
    forks: 310,
    visibility: "public",
    updatedAt: "Jun 2, 2026",
    url: "#",
  },
  {
    id: 6,
    name: "cli-toolkit",
    description: "A powerful CLI toolkit for developer workflows and automation.",
    language: "Go",
    stars: 660,
    forks: 84,
    visibility: "public",
    updatedAt: "May 28, 2026",
    url: "#",
  },
  {
    id: 7,
    name: "style-system",
    description: "Design tokens and component primitives for building consistent UIs.",
    language: "CSS",
    stars: 430,
    forks: 58,
    visibility: "public",
    updatedAt: "May 20, 2026",
    url: "#",
  },
  {
    id: 8,
    name: "data-pipeline",
    description: "Scalable ETL pipeline framework built for analytics workloads.",
    language: "Python",
    stars: 1100,
    forks: 210,
    visibility: "public",
    updatedAt: "May 14, 2026",
    url: "#",
  },
  {
    id: 9,
    name: "auth-service",
    description: "Lightweight authentication microservice with JWT and OAuth2 support.",
    language: "Go",
    stars: 780,
    forks: 130,
    visibility: "public",
    updatedAt: "Apr 30, 2026",
    url: "#",
  },
  {
    id: 10,
    name: "infra-scripts",
    description: "Infrastructure automation scripts for cloud deployments and CI/CD.",
    language: "Shell",
    stars: 290,
    forks: 47,
    visibility: "public",
    updatedAt: "Apr 20, 2026",
    url: "#",
  },
];
